# Generated by Django 3.0.8 on 2020-08-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200818_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwatchdashboardmodel',
            name='watched_creator',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userwatchdashboardmodel',
            name='watched_sponsor',
            field=models.TextField(null=True),
        ),
    ]
