# Generated by Django 3.0.8 on 2020-08-19 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userwatchdashboardmodel_idk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwatchdashboardmodel',
            name='idk',
        ),
    ]
