# Generated by Django 3.0.8 on 2020-08-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0010_auto_20200816_2040'),
        ('users', '0013_remove_userwatchdashboardmodel_idk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwatchdashboardmodel',
            name='watched_creator',
        ),
        migrations.AddField(
            model_name='userwatchdashboardmodel',
            name='watched_creator',
            field=models.ManyToManyField(blank=True, to='creator_listings.BlogListingCreationModel'),
        ),
    ]
