# Generated by Django 3.0.8 on 2020-08-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0010_auto_20200816_2040'),
        ('sponsor_listings', '0007_auto_20200816_2040'),
        ('users', '0016_auto_20200820_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Profile',
            name='creators_watched',
            field=models.ManyToManyField(blank=True, related_name='creators_watching', to='creator_listings.BlogListingCreationModel'),
        ),
        migrations.AlterField(
            model_name='Profile',
            name='sponsors_watched',
            field=models.ManyToManyField(blank=True, related_name='sponsors_watching', to='sponsor_listings.SponsorListingCreationModel'),
        ),
    ]
