# Generated by Django 3.0.8 on 2020-08-20 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0010_auto_20200816_2040'),
        ('sponsor_listings', '0007_auto_20200816_2040'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0019_auto_20200820_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, choices=[('watch', 'watch'), ('watching', 'watching')], max_length=50)),
                ('creator_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator_listings.BlogListingCreationModel')),
                ('sponsor_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor_listings.SponsorListingCreationModel')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
