# Generated by Django 3.0.8 on 2020-08-20 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_watch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watch',
        ),
    ]
