# Generated by Django 3.0.8 on 2020-08-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0007_auto_20200816_2040'),
        ('creator_listings', '0010_auto_20200816_2040'),
        ('users', '0021_delete_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='Profile',
            name='ordered_creators',
            field=models.ManyToManyField(blank=True, related_name='creators_ordered', to='creator_listings.BlogListingCreationModel'),
        ),
        migrations.AddField(
            model_name='Profile',
            name='ordered_sponsors',
            field=models.ManyToManyField(blank=True, related_name='sponsors_ordered', to='sponsor_listings.SponsorListingCreationModel'),
        ),
    ]
