# Generated by Django 3.0.8 on 2020-08-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0007_auto_20200816_2040'),
        ('users', '0023_auto_20200821_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Profile',
            name='sponsors_who_ordered_u',
            field=models.ManyToManyField(blank=True, related_name='sponsors_who_ordered_u', to='sponsor_listings.SponsorListingCreationModel'),
        ),
    ]
