# Generated by Django 3.0.8 on 2020-08-22 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creator_listings', '0010_auto_20200816_2040'),
        ('sponsor_listings', '0007_auto_20200816_2040'),
        ('users', '0024_auto_20200821_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Sponsor_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_creator_is_willing_to_provide', models.CharField(max_length=500)),
                ('services_creator_is_willing_to_provide_detailed', models.TextField(blank=True, max_length=1000)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('buyers_listing_for_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator_listings.BlogListingCreationModel')),
                ('sponsor_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor_listings.SponsorListingCreationModel')),
            ],
        ),
        migrations.CreateModel(
            name='Creator_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_services_sponsor_is_looking_for', models.CharField(max_length=500)),
                ('what_services_sponsor_is_looking_for_detailed', models.TextField(blank=True, max_length=1000)),
                ('what_services_creator_is_looking_for', models.CharField(max_length=500)),
                ('what_services_creator_is_looking_fordetailed', models.TextField(blank=True, max_length=1000)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('buyers_listing_for_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers_creator_listing', to='creator_listings.BlogListingCreationModel')),
                ('buyers_listing_for_sponsor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sponsor_listings.SponsorListingCreationModel')),
                ('creator_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_listing', to='creator_listings.BlogListingCreationModel')),
            ],
        ),
    ]
