# Generated by Django 3.0.8 on 2020-08-22 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0010_auto_20200816_2040'),
        ('users', '0025_auto_20200821_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator_order',
            name='buyers_listing_for_creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers_creator_listing', to='creator_listings.BlogListingCreationModel'),
        ),
    ]
