# Generated by Django 3.0.8 on 2020-08-23 01:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sponsor_listings', '0007_auto_20200816_2040'),
        ('creator_listings', '0010_auto_20200816_2040'),
        ('users', '0028_auto_20200821_2132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creator_Order',
            new_name='CreatorOrderModel',
        ),
        migrations.RenameModel(
            old_name='Sponsor_Order',
            new_name='SponsorOrderModel',
        ),
    ]
