# Generated by Django 3.0.8 on 2020-08-23 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20200822_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorordermodel',
            name='buyers_listing_for_creator',
        ),
        migrations.RemoveField(
            model_name='creatorordermodel',
            name='what_services_creator_is_looking_for',
        ),
        migrations.RemoveField(
            model_name='creatorordermodel',
            name='what_services_creator_is_looking_fordetailed',
        ),
    ]
