# Generated by Django 3.0.8 on 2020-08-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20200823_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatorordermodel',
            old_name='buyers_listing_for_sponsor',
            new_name='buyers_listing',
        ),
        migrations.RenameField(
            model_name='creatorordermodel',
            old_name='what_services_sponsor_is_looking_for',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='creatorordermodel',
            old_name='what_services_sponsor_is_looking_for_detailed',
            new_name='service_detailed',
        ),
    ]
