# Generated by Django 3.0.8 on 2020-08-23 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0010_auto_20200816_2040'),
        ('users', '0031_auto_20200823_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorordermodel',
            name='buyers_listing',
        ),
        migrations.AddField(
            model_name='creatorordermodel',
            name='buyers_listing_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creator_listings.BlogListingCreationModel'),
        ),
    ]
