# Generated by Django 3.0.8 on 2020-08-23 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0010_auto_20200816_2040'),
        ('sponsor_listings', '0007_auto_20200816_2040'),
        ('users', '0032_auto_20200823_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorordermodel',
            name='buyers_listing_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creator_listings.BlogListingCreationModel'),
        ),
        migrations.AlterField(
            model_name='creatorordermodel',
            name='buyers_listing_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsor_listings.SponsorListingCreationModel'),
        ),
    ]
