# Generated by Django 3.0.8 on 2020-08-23 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0036_auto_20200823_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorordermodel',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_username', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creatorordermodel',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_username', to=settings.AUTH_USER_MODEL),
        ),
    ]
