# Generated by Django 3.0.8 on 2020-08-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20200823_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorordermodel',
            name='creator',
        ),
    ]
