# Generated by Django 3.0.8 on 2020-08-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_remove_creatorordermodel_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorordermodel',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='creatorordermodel',
            name='creator_listing',
        ),
    ]
