# Generated by Django 3.0.8 on 2020-08-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20200823_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorordermodel',
            name='buyer_listing',
        ),
        migrations.RemoveField(
            model_name='creatorordermodel',
            name='buyers_listing_c',
        ),
        migrations.RemoveField(
            model_name='creatorordermodel',
            name='buyers_listing_s',
        ),
        migrations.RemoveField(
            model_name='creatorordermodel',
            name='service',
        ),
    ]
