# Generated by Django 3.0.8 on 2020-08-23 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creator_listings', '0010_auto_20200816_2040'),
        ('sponsor_listings', '0007_auto_20200816_2040'),
        ('users', '0040_auto_20200823_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorordermodel',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_username', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creatorordermodel',
            name='buyer_listing',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='creatorordermodel',
            name='buyers_listing_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creator_listings.BlogListingCreationModel'),
        ),
        migrations.AddField(
            model_name='creatorordermodel',
            name='buyers_listing_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsor_listings.SponsorListingCreationModel'),
        ),
        migrations.AddField(
            model_name='creatorordermodel',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_username', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creatorordermodel',
            name='creator_listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_listing', to='creator_listings.BlogListingCreationModel'),
        ),
        migrations.AddField(
            model_name='creatorordermodel',
            name='service',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
