# Generated by Django 3.0.8 on 2020-08-23 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0042_remove_creatorordermodel_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorordermodel',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_username', to=settings.AUTH_USER_MODEL),
        ),
    ]
