# Generated by Django 3.0.8 on 2020-08-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_creatorordermodel_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorordermodel',
            name='buyer_listing',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
