# Generated by Django 3.0.8 on 2020-08-27 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creator_listings', '0010_auto_20200816_2040'),
        ('sponsor_listings', '0007_auto_20200816_2040'),
        ('users', '0047_auto_20200825_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorordermodel',
            name='buyers_listing_for_creator',
        ),
        migrations.AddField(
            model_name='sponsorordermodel',
            name='buyer_listing',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sponsorordermodel',
            name='buyers_listing_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers_c_listing_for_s_order', to='creator_listings.BlogListingCreationModel'),
        ),
        migrations.AddField(
            model_name='sponsorordermodel',
            name='buyers_listing_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers_s_listing_for_s_order', to='sponsor_listings.SponsorListingCreationModel'),
        ),
        migrations.AddField(
            model_name='sponsorordermodel',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_username_sponsor_listing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creatorordermodel',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_username_creator_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creatorordermodel',
            name='buyers_listing_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers_c_listing_for_c_order', to='creator_listings.BlogListingCreationModel'),
        ),
        migrations.AlterField(
            model_name='creatorordermodel',
            name='buyers_listing_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers_s_listing_for_c_order', to='sponsor_listings.SponsorListingCreationModel'),
        ),
        migrations.AlterField(
            model_name='creatorordermodel',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_username_creator_listing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sponsorordermodel',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_username_sponsor_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sponsorordermodel',
            name='sponsor_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_listing', to='sponsor_listings.SponsorListingCreationModel'),
        ),
    ]
