# Generated by Django 3.0.8 on 2020-08-27 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sponsor_listings', '0007_auto_20200816_2040'),
        ('users', '0048_auto_20200826_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorordermodel',
            name='buyer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_username_sponsor_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sponsorordermodel',
            name='sponsor_listing',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_listing', to='sponsor_listings.SponsorListingCreationModel'),
        ),
    ]
