# Generated by Django 3.0.8 on 2020-08-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20200826_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorordermodel',
            name='status',
            field=models.CharField(blank=True, default='In Review', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sponsorordermodel',
            name='status',
            field=models.CharField(blank=True, default='In Review', max_length=100, null=True),
        ),
    ]
