# Generated by Django 3.0.8 on 2020-08-31 00:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0007_auto_20200816_2040'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creator_listings', '0010_auto_20200816_2040'),
        ('users', '0053_completedorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletedOrder',
            new_name='CompletedOrderModel',
        ),
    ]
