# Generated by Django 3.0.8 on 2020-09-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_featureticket_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureticket',
            name='feature',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='problem',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
