# Generated by Django 3.0.8 on 2020-09-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_auto_20200916_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureticket',
            name='feature',
        ),
    ]
