# Generated by Django 3.0.8 on 2020-09-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_remove_featureticket_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureticket',
            name='feature',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
