# Generated by Django 3.0.8 on 2020-09-29 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0058_featureticket_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureticket',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_request_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featureticket',
            name='email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_ticket_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
