# Generated by Django 3.0.8 on 2020-10-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_auto_20200928_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcreatorordermodel',
            name='who_initiated_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
