# Generated by Django 3.0.8 on 2020-10-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_acceptedcreatorordermodel_who_initiated_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedordermodel',
            name='who_initiated_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
