# Generated by Django 3.0.8 on 2020-10-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_completedordermodel_who_initiated_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcreatorordermodel',
            name='sponsor_change',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
