# Generated by Django 3.0.8 on 2020-10-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_acceptedcreatorordermodel_sponsor_approves'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcreatorordermodel',
            name='turn',
            field=models.FloatField(default=1, max_length=1000),
        ),
    ]
