# Generated by Django 3.0.8 on 2020-10-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_acceptedcreatorordermodel_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcreatorordermodel',
            name='edits',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
