# Generated by Django 3.0.8 on 2020-10-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_remove_acceptedcreatorordermodel_sponsor_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcreatorordermodel',
            name='review_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='review/'),
        ),
    ]
