# Generated by Django 3.0.8 on 2020-10-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_acceptedcreatorordermodel_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedcreatorordermodel',
            name='payout',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
