# Generated by Django 3.0.8 on 2020-10-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_auto_20201013_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptedcreatorordermodel',
            name='payout',
        ),
        migrations.AlterField(
            model_name='acceptedcreatorordermodel',
            name='edits',
            field=models.CharField(blank=True, default=0, max_length=10000, null=True),
        ),
    ]
