# Generated by Django 3.0.8 on 2020-10-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_auto_20201013_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcreatorordermodel',
            name='payout',
            field=models.CharField(blank=True, default=0, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='acceptedcreatorordermodel',
            name='edits',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
