# Generated by Django 3.0.8 on 2020-10-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_auto_20201013_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorordermodel',
            name='payout',
            field=models.CharField(blank=True, default=0, max_length=10000, null=True),
        ),
    ]
