# Generated by Django 3.0.8 on 2020-10-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_creatorordermodel_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedordermodel',
            name='payout',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
