# Generated by Django 3.0.8 on 2020-10-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_completedordermodel_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=320, null=True),
        ),
    ]
