# Generated by Django 3.0.8 on 2020-10-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(blank=True, default='none', max_length=320, null=True),
        ),
    ]
