# Generated by Django 3.0.8 on 2020-11-07 00:53

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_auto_20201022_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedcreatorordermodel',
            name='review_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=users.models.AcceptedCreatorOrderModel.review_file_path),
        ),
    ]
