# Generated by Django 3.0.8 on 2020-11-08 03:19

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_creatorordermodel_s_content_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcreatorordermodel',
            name='s_content_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=users.models.AcceptedCreatorOrderModel.s_content_file_path),
        ),
    ]
