# Generated by Django 3.0.8 on 2020-11-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0079_acceptedcreatorordermodel_s_content_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcreatorordermodel',
            name='token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='acceptedcreatorordermodel',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
