# Generated by Django 3.0.8 on 2020-11-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_auto_20201109_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedcreatorordermodel',
            name='token',
            field=models.BinaryField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='acceptedcreatorordermodel',
            name='transaction_id',
            field=models.BinaryField(blank=True, max_length=1000, null=True),
        ),
    ]
