# Generated by Django 3.0.8 on 2020-11-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_auto_20201109_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedcreatorordermodel',
            name='transaction_id',
            field=models.BinaryField(blank=True, editable=True, max_length=1000, null=True),
        ),
    ]
