# Generated by Django 3.0.8 on 2020-11-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0083_auto_20201109_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcreatorordermodel',
            name='escrow_stage',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
