# Generated by Django 3.0.8 on 2020-11-15 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_acceptedcreatorordermodel_escrow_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptedcreatorordermodel',
            old_name='escrow_stage',
            new_name='stage',
        ),
    ]
