# Generated by Django 3.0.8 on 2020-11-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='creator',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
