# Generated by Django 3.0.8 on 2020-12-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0088_remove_supportticket_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='acceptedcreatorordermodel',
            name='content_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
