# Generated by Django 3.1.3 on 2021-01-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_auto_20201202_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedcreatorordermodel',
            name='token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='acceptedcreatorordermodel',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
