# Generated by Django 3.1.3 on 2021-01-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0090_auto_20210104_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorordermodel',
            name='services_creator_is_willing_to_provide',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
