# Generated by Django 3.0.8 on 2020-08-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogListingCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_url', models.CharField(max_length=300)),
                ('niche', models.CharField(max_length=300)),
                ('age', models.IntegerField())

            ],
        ),
    ]
