# Generated by Django 3.0.8 on 2020-08-11 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogListingCreation',
            new_name='BlogListingCreationModel',
        ),
    ]
