# Generated by Django 3.0.8 on 2020-08-16 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0006_auto_20200815_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloglistingcreationmodel',
            old_name='blog_url',
            new_name='blog_name',
        ),
    ]
