# Generated by Django 3.0.8 on 2020-08-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0008_auto_20200816_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='blog_catagory',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='blog_name',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='description',
            field=models.CharField(default=None, max_length=30000),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='language',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='age',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='blog_url',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='monthly_views',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='niche',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
