# Generated by Django 3.0.8 on 2020-08-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0009_auto_20200816_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglistingcreationmodel',
            name='blog_catagory',
        ),
        migrations.RemoveField(
            model_name='bloglistingcreationmodel',
            name='blog_name',
        ),
        migrations.RemoveField(
            model_name='bloglistingcreationmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bloglistingcreationmodel',
            name='language',
        ),
    ]
