# Generated by Django 3.0.8 on 2020-09-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0010_auto_20200816_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='niche',
            field=models.BooleanField(default=None),
        ),
    ]
