# Generated by Django 3.1.3 on 2021-01-11 19:51

import creator_listings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creator_listings', '0010_auto_20200816_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='audience_description',
            field=models.TextField(blank=True, default=None, max_length=500000, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='blog_name',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='blog_type',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='domain_authority',
            field=models.IntegerField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='exp_description',
            field=models.TextField(blank=True, default=None, max_length=500000, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='google_a_csv',
            field=models.FileField(blank=True, default=None, null=True, upload_to=creator_listings.models.BlogListingCreationModel.google_a_csv_upload_path),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='listing_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=creator_listings.models.BlogListingCreationModel.listing_img_path),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='notification_type_email',
            field=models.CharField(blank=True, default=None, max_length=30000, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='notification_type_phone',
            field=models.CharField(blank=True, default=None, max_length=30000, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='number',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='overview_description',
            field=models.TextField(blank=True, default=None, max_length=500000, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='pricing_description',
            field=models.TextField(blank=True, default=None, max_length=500000, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='search_keywords',
            field=models.CharField(blank=True, default=None, max_length=30000, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='sponsor_description',
            field=models.TextField(blank=True, default=None, max_length=500000, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='tagline',
            field=models.CharField(blank=True, default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='age',
            field=models.IntegerField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='blog_url',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='monthly_views',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='niche',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
