# Generated by Django 3.0.8 on 2020-09-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0012_auto_20200904_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='blog_name',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='blog_type',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=30000, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
