# Generated by Django 3.0.8 on 2020-09-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0013_auto_20200909_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='google_a_csv',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
