# Generated by Django 3.0.8 on 2020-09-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0014_bloglistingcreationmodel_google_a_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='creator_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='paypal_email',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
