# Generated by Django 3.0.8 on 2020-09-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0014_bloglistingcreationmodel_google_a_csv'),
    ]

    operations = [
        
    ]
