# Generated by Django 3.0.8 on 2020-09-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0014_bloglistingcreationmodel_google_a_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglistingcreationmodel',
            name='description',
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='audience_description',
            field=models.CharField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='overview_description',
            field=models.CharField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='sponsor_description',
            field=models.CharField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='tagline',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
