# Generated by Django 3.0.8 on 2020-09-12 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creator_listings', '0016_auto_20200912_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
