# Generated by Django 3.0.8 on 2020-09-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0017_auto_20200912_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='age',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='blog_url',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='niche',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
