# Generated by Django 3.0.8 on 2020-09-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0018_auto_20200912_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='number',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
