# Generated by Django 3.0.8 on 2020-09-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0019_auto_20200912_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='creator_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='google_a_csv',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
