# Generated by Django 3.0.8 on 2020-09-25 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0020_auto_20200912_2037'),
        ('creator_listings', '0015_auto_20200912_1834'),
    ]

    operations = [
    ]
