# Generated by Django 3.0.8 on 2020-09-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0021_merge_20200925_1720'),
    ]

    operations = [
        
    ]
