# Generated by Django 3.0.8 on 2020-09-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0022_auto_20200926_1633'),
    ]

    operations = [
        
    ]
