# Generated by Django 3.0.8 on 2020-10-14 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0023_auto_20200926_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglistingcreationmodel',
            name='email',
        ),
    ]
