# Generated by Django 3.0.8 on 2020-10-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0024_remove_bloglistingcreationmodel_creator_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglistingcreationmodel',
            name='paypal_email',
        ),
    ]
