# Generated by Django 3.0.8 on 2020-10-14 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0025_remove_bloglistingcreationmodel_paypal_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglistingcreationmodel',
            name='email',
        ),
    ]
