# Generated by Django 3.0.8 on 2020-11-07 00:25

import creator_listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0025_auto_20201016_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='listing_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=creator_listings.models.BlogListingCreationModel.listing_img_path),
        ),
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='google_a_csv',
            field=models.FileField(blank=True, default=None, null=True, upload_to=creator_listings.models.BlogListingCreationModel.google_a_csv_upload_path),
        ),
    ]
