# Generated by Django 3.0.8 on 2020-11-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0026_auto_20201106_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='notification_type',
            field=models.CharField(blank=True, default=None, max_length=30000, null=True),
        ),
    ]
