# Generated by Django 3.0.8 on 2020-11-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0027_bloglistingcreationmodel_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='search_keywords',
            field=models.CharField(blank=True, default=None, max_length=30000, null=True),
        ),
    ]
