# Generated by Django 3.0.8 on 2020-11-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0028_bloglistingcreationmodel_search_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
