# Generated by Django 3.0.8 on 2020-11-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0029_bloglistingcreationmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='age',
            field=models.IntegerField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
