# Generated by Django 3.0.8 on 2020-11-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0030_auto_20201113_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='audience_description',
            field=models.TextField(blank=True, default=None, max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='overview_description',
            field=models.TextField(blank=True, default=None, max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='sponsor_description',
            field=models.TextField(blank=True, default=None, max_length=500000, null=True),
        ),
    ]
