# Generated by Django 3.0.8 on 2020-11-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0031_auto_20201117_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloglistingcreationmodel',
            old_name='notification_type',
            new_name='notification_type_email',
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='notification_type_phone',
            field=models.CharField(blank=True, default=None, max_length=30000, null=True),
        ),
    ]
