# Generated by Django 3.0.8 on 2020-11-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0032_auto_20201122_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='domain_authority',
            field=models.IntegerField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
