# Generated by Django 3.1.3 on 2021-01-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0034_auto_20201202_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='pricing_description',
            field=models.TextField(blank=True, default=None, max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='tagline',
            field=models.CharField(blank=True, default=None, max_length=10000, null=True),
        ),
    ]
