# Generated by Django 3.1.3 on 2021-01-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0035_auto_20210105_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='exp_description',
            field=models.TextField(blank=True, default=None, max_length=500000, null=True),
        ),
    ]
