# Generated by Django 3.1.3 on 2021-01-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0036_bloglistingcreationmodel_exp_description'),
        ('creator_listings', '0011_auto_20210111_1451'),
    ]

    operations = [
    ]
