# Generated by Django 3.1.3 on 2021-01-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0037_merge_20210111_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglistingcreationmodel',
            name='domain_authority',
        ),
    ]
