# Generated by Django 3.1.3 on 2021-01-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0038_remove_bloglistingcreationmodel_domain_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='avg_comments',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='avg_likes',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='engagement_rate',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='estimated_post_imppressions',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingcreationmodel',
            name='followers',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
