# Generated by Django 3.1.3 on 2021-01-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0039_auto_20210111_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloglistingcreationmodel',
            old_name='blog_name',
            new_name='ig_name',
        ),
        migrations.RenameField(
            model_name='bloglistingcreationmodel',
            old_name='blog_type',
            new_name='ig_type',
        ),
        migrations.RenameField(
            model_name='bloglistingcreationmodel',
            old_name='blog_url',
            new_name='ig_url',
        ),
    ]
