# Generated by Django 3.1.3 on 2021-01-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0040_auto_20210111_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloglistingcreationmodel',
            old_name='estimated_post_imppressions',
            new_name='estimated_post_impressions',
        ),
    ]
