# Generated by Django 3.1.3 on 2021-01-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0041_auto_20210111_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglistingcreationmodel',
            name='google_a_csv',
        ),
    ]
