# Generated by Django 3.1.3 on 2021-01-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_listings', '0043_auto_20210111_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglistingcreationmodel',
            name='avg_comments',
        ),
        migrations.AlterField(
            model_name='bloglistingcreationmodel',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
