# Generated by Django 3.0.8 on 2020-08-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='money',
            field=models.IntegerField(error_messages={'blank': 'Fill this in', 'invalid': 'Input a number'}),
        ),
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='monthly_views_min',
            field=models.CharField(error_messages={'blank': 'Fill this in', 'invalid': 'Input text'}, max_length=300),
        ),
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='niche',
            field=models.CharField(error_messages={'blank': 'Fill this in', 'invalid': 'Input text'}, max_length=300),
        ),
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='product',
            field=models.CharField(error_messages={'blank': 'Fill this in', 'invalid': 'Input text'}, max_length=300),
        ),
    ]
