# Generated by Django 3.0.8 on 2020-08-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0002_auto_20200814_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='product',
            field=models.CharField(error_messages={'blank': 'Fill this in', 'invalid': 'Input text'}, max_length=3),
        ),
    ]
