# Generated by Django 3.0.8 on 2020-08-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0003_auto_20200814_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='money',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='monthly_views_min',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='niche',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='product',
            field=models.CharField(max_length=300),
        ),
    ]
