# Generated by Django 3.0.8 on 2020-08-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0005_sponsorlistingcreationmodel_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlistingcreationmodel',
            name='look_blog_type',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='sponsorlistingcreationmodel',
            name='look_language',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='sponsorlistingcreationmodel',
            name='look_site_age',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='money',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='monthly_views_min',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='niche',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='product',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
