# Generated by Django 3.0.8 on 2020-08-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0006_auto_20200816_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorlistingcreationmodel',
            name='look_blog_type',
        ),
        migrations.RemoveField(
            model_name='sponsorlistingcreationmodel',
            name='look_language',
        ),
        migrations.RemoveField(
            model_name='sponsorlistingcreationmodel',
            name='look_site_age',
        ),
    ]
