# Generated by Django 3.0.8 on 2020-09-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0007_auto_20200816_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlistingcreationmodel',
            name='audience_description',
            field=models.CharField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='sponsorlistingcreationmodel',
            name='creator_description',
            field=models.CharField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='sponsorlistingcreationmodel',
            name='overview_description',
            field=models.CharField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='sponsorlistingcreationmodel',
            name='pic',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='sponsorlistingcreationmodel',
            name='tagline',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
