# Generated by Django 3.0.8 on 2020-09-14 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0008_auto_20200914_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsorlistingcreationmodel',
            old_name='pic',
            new_name='sponsor_img',
        ),
    ]
