# Generated by Django 3.0.8 on 2020-09-14 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sponsor_listings', '0009_auto_20200914_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='monthly_views_min',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
