# Generated by Django 3.0.8 on 2020-09-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0010_auto_20200914_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='money',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='niche',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='product',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
