# Generated by Django 3.0.8 on 2020-10-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0011_auto_20200927_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlistingcreationmodel',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
