# Generated by Django 3.0.8 on 2020-10-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0012_sponsorlistingcreationmodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
