# Generated by Django 3.0.8 on 2020-11-07 00:34

from django.db import migrations, models
import sponsor_listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0013_auto_20201016_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorlistingcreationmodel',
            name='sponsor_img',
        ),
        migrations.AddField(
            model_name='sponsorlistingcreationmodel',
            name='listing_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=sponsor_listings.models.SponsorListingCreationModel.listing_img_path),
        ),
    ]
