# Generated by Django 3.0.8 on 2020-11-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0014_auto_20201106_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlistingcreationmodel',
            name='notification_type',
            field=models.CharField(blank=True, default=None, max_length=30000, null=True),
        ),
    ]
