# Generated by Django 3.0.8 on 2020-11-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0015_sponsorlistingcreationmodel_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlistingcreationmodel',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sponsorlistingcreationmodel',
            name='number',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
