# Generated by Django 3.0.8 on 2020-11-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0016_auto_20201112_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlistingcreationmodel',
            name='search_keywords',
            field=models.CharField(blank=True, default=None, max_length=30000, null=True),
        ),
    ]
