# Generated by Django 3.0.8 on 2020-11-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0017_sponsorlistingcreationmodel_search_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='audience_description',
            field=models.TextField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='creator_description',
            field=models.TextField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorlistingcreationmodel',
            name='overview_description',
            field=models.TextField(blank=True, default=None, max_length=50000, null=True),
        ),
    ]
