# Generated by Django 3.0.8 on 2020-11-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0018_auto_20201117_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsorlistingcreationmodel',
            old_name='notification_type',
            new_name='notification_type_email',
        ),
        migrations.AddField(
            model_name='sponsorlistingcreationmodel',
            name='notification_type_phone',
            field=models.CharField(blank=True, default=None, max_length=30000, null=True),
        ),
    ]
