# Generated by Django 3.0.8 on 2020-12-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0019_auto_20201122_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlistingcreationmodel',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
