# Generated by Django 3.1.3 on 2021-01-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0020_sponsorlistingcreationmodel_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlistingcreationmodel',
            name='pricing_description',
            field=models.TextField(blank=True, default=None, max_length=500000, null=True),
        ),
    ]
