# Generated by Django 3.1.3 on 2021-01-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_listings', '0021_sponsorlistingcreationmodel_pricing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlistingcreationmodel',
            name='exp_description',
            field=models.TextField(blank=True, default=None, max_length=50000, null=True),
        ),
    ]
