# Generated by Django 3.1.3 on 2021-01-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatoraccsponsormetricmodel',
            name='acc_order_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='creatoraccsponsormetricmodel',
            name='c_order_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='sponsororderscreatormetricmodel',
            name='acc_order_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='sponsororderscreatormetricmodel',
            name='s_order_id',
            field=models.IntegerField(default=-1),
        ),
    ]
