# Generated by Django 3.1.3 on 2021-01-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_auto_20210104_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatoraccsponsormetricmodel',
            old_name='acc_order_id',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='sponsororderscreatormetricmodel',
            old_name='acc_order_id',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='creatoraccsponsormetricmodel',
            name='c_order_id',
        ),
        migrations.RemoveField(
            model_name='sponsororderscreatormetricmodel',
            name='s_order_id',
        ),
    ]
