# Generated by Django 3.1.3 on 2021-01-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_auto_20210102_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorlistingmademetricmodel',
            name='niche',
        ),
        migrations.RemoveField(
            model_name='creatorlistingmademetricmodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='creatorlistingmademetricmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sponsorlistingmademetricmodel',
            name='niche',
        ),
        migrations.RemoveField(
            model_name='sponsorlistingmademetricmodel',
            name='user',
        ),
    ]
