# Generated by Django 3.1.3 on 2021-01-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_auto_20210103_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorlistingmademetricmodel',
            name='listing_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='sponsorlistingmademetricmodel',
            name='listing_id',
            field=models.IntegerField(default=-1),
        ),
    ]
