# Generated by Django 3.1.3 on 2021-01-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_auto_20210104_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatoraccsponsormetricmodel',
            old_name='order_id',
            new_name='acc_order_id',
        ),
        migrations.RenameField(
            model_name='sponsoracccreatormetricmodel',
            old_name='order_id',
            new_name='acc_order_id',
        ),
        migrations.AddField(
            model_name='creatoraccsponsormetricmodel',
            name='c_order_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='sponsoracccreatormetricmodel',
            name='s_order_id',
            field=models.IntegerField(default=-1),
        ),
    ]
