# Generated by Django 3.1.3 on 2021-01-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_auto_20210104_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatoraccsponsormetricmodel',
            old_name='acc_order_id',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='creatoraccsponsormetricmodel',
            name='c_order_id',
        ),
        migrations.RemoveField(
            model_name='sponsoracccreatormetricmodel',
            name='acc_order_id',
        ),
        migrations.RemoveField(
            model_name='sponsoracccreatormetricmodel',
            name='s_order_id',
        ),
    ]
