# Generated by Django 3.1.3 on 2021-01-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_auto_20210103_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorlistingmademetricmodel',
            name='ga_bool',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
