# Generated by Django 3.1.3 on 2021-01-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_auto_20210104_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatoraccsponsormetricmodel',
            name='order_id',
        ),
    ]
