# Generated by Django 3.1.3 on 2021-01-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_auto_20210104_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoracccreatormetricmodel',
            name='acc_order_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='sponsoracccreatormetricmodel',
            name='s_order_id',
            field=models.IntegerField(default=-1),
        ),
    ]
