# Generated by Django 3.1.3 on 2021-01-04 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0008_auto_20210104_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeordermetricmodel',
            name='order_id',
        ),
    ]
