# Generated by Django 3.1.3 on 2021-01-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0009_remove_completeordermetricmodel_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeordermetricmodel',
            name='acc_order_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='completeordermetricmodel',
            name='completed_order_id',
            field=models.IntegerField(default=-1),
        ),
    ]
